# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - env:
      - CGO_ENABLED=0
    binary: tapeless
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X tapeless.app/tapeless-cli/env.Version={{.Version}}
      - -X tapeless.app/tapeless-cli/env.ApiURL=https://api.tapeless.app/cli/v1
      - -X tapeless.app/tapeless-cli/env.WebURL=https://tapeless.app
      - -X tapeless.app/tapeless-cli/env.LoginCallbackPort=8080

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      tapeless_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: tapeless
    commit_author:
      name: Tapeless
      email: info@tapeless.app
    homepage: https://tapeless.app
    description: Tapeless CLI
    license: proprietary
    test: |
      assert_match version.to_s, shell_output("#{bin}/tapeless version")
    install: |
      bin.install "tapeless"
    repository:
      owner: Tapeless-App
      name: homebrew-tapeless-cli

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
